# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.12,)" # Require at least 1.9.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId= "ezcraft"
version="${file.jarVersion}"
displayName="ezcraft"
credits="The ezcraft dev team"
authors="ezcraftAuthor"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.ezcraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ezcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
